### ISSUE TITLE
Stop receiving updates eventually

### ISSUE THREAD

**Issue by milch** [nikat/mtproto2json#1]
Hi,

First of all let me thank you for this project, it's helped me a lot in integrating Telegram in a personal project of mine. 

My issue is, as the title says, that eventually I just stop receiving updates. Sometimes a message sent to my account will be delayed for 30s or more and arrive together with another message that was sent later. Do you know if there is any way to ensure that I can keep receiving updates? I tried sending a `getDialogs` every 60s or so but that doesn't always work.

**Comment by lattenwald** [comment]
Hi @milch,

In my pet project I send [account.updateStatus](https://core.telegram.org/method/account.updateStatus) message to set `offline` status to `false` every 60 seconds, and this might be the reason I get all updates.

**Comment by milch** [comment]
Thanks for the response! 

Do you get all the updates in time as well or are some of them delayed? I started calling and handling `updates.getDifferences` now and now I seem to get everything finally, but I'm also still seeing long delays before I get messages sometimes (30s or longer)

**Comment by lattenwald** [comment]
No, I don't think there was any delay. I am using this library for playing a game, which can be pretty sensitive to delays of 5+ seconds, and I didn't have any problems with that.

**Comment by nikat** [comment]
Hello!

Please try enabling --verbose switch with streamjson.py. You will see a log of events like on this screenshot:

![image](https://user-images.githubusercontent.com/10208173/35212278-a9641188-ff6a-11e7-912c-13fcdd34806d.png)

To understand this log, use this legend for arrow sign marks:

- **^** — messages sent to Telegram
- **v** — messages received from Telegram
- **>** — messages received from JSON client
- **<** — messages sent to JSON client

There are two possibilities: either the issue is caused by a bug in my code, or the 30+s lag is how Telegram API responds to your requests. In the former case you will probably see a delay between a message received from Telegram (marked by **v** in the log) and a message sent to JSON client (marked by **<** sign). In the latter case you will notice no delay between those.

Unfortunately Telegram API itself is poorly documented and there is no clarity how Telegram servers decide if your session is active. Either way I would suggest you to experiment with scheme.tl methods, for example **account.updateStatus**, like @lattenwald suggests. I think the corresponding JSON request should look like this (pls correct me if I'm wrong):

`{"message": {"_cons": "account.updateStatus", "offline":{"_cons": "boolFalse"}}`

Good luck with your project!

**Comment by milch** [comment]
Alright, thanks for all your help! I debugged a bit with the `--verbose` enabled, seems the delay comes from Telegram. I added the `account.updateStatus` message every 30s, on top of handling `updates.getDifference` and `updates.getChannelDifference` correctly (by keeping track of the `pts`, `seq`, and `date`) and marking messages the client has processed as read. 

With all of those, it seems I finally continue getting all messages. There's still delays sometimes, but seems that those are just random
